name: Release mosdns

on:
  push:
    tags:
      - 'v*'  # 触发条件为带 "v" 前缀的标签
  workflow_dispatch:  # 允许手动触发

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      # 1. 克隆指定的仓库
      - name: Clone repository
        run: |
          git clone --depth 1 https://github.com/irineSistiana/mosdns.git
          cd mosdns
          git fetch --tags
          git checkout ${{ github.ref_name }}

      # 2. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          check-latest: true
          cache: true

      # 3. 编译代码
      - name: Build mosdns
        run: |
          cd mosdns
          mkdir -p release
          GOOS=linux GOARCH=amd64 go build -o release/mosdns-linux-amd64
          GOOS=windows GOARCH=amd64 go build -o release/mosdns-windows-amd64.exe
          GOOS=darwin GOARCH=amd64 go build -o release/mosdns-darwin-amd64
          zip release/mosdns-linux-amd64.zip release/mosdns-linux-amd64
          zip release/mosdns-windows-amd64.zip release/mosdns-windows-amd64.exe
          zip release/mosdns-darwin-amd64.zip release/mosdns-darwin-amd64

      # 4. 发布到 GitHub Releases
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            mosdns/release/mosdns-linux-amd64.zip
            mosdns/release/mosdns-windows-amd64.zip
            mosdns/release/mosdns-darwin-amd64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
