name: Release mosdns

on:
  push:
    tags:
      - 'v*'  # 触发条件：推送带 "v" 前缀的标签
  workflow_dispatch:  # 手动触发支持

jobs:
  build-release:
    runs-on: ubuntu-latest

    steps:
      # 1. 克隆仓库
      - name: Clone repository
        run: |
          git clone --depth 1 https://github.com/irineSistiana/mosdns.git
          cd mosdns
          git fetch --tags
          git checkout ${{ github.ref_name }}

      # 2. 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.23'
          check-latest: true
          cache: true

      # 4. 安装 Python 依赖（如果有 requirements.txt）
      - name: Install Python dependencies
        run: |
          cd mosdns
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      # 5. 调用 release.py 脚本编译
      - name: Build mosdns
        run: |
          cd mosdns
          python ./release.py
        env:
          CGO_ENABLED: '0'  # 禁用 CGO 加快编译

      # 6. 发布到 Release
      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: './mosdns/release/mosdns*.zip'  # 根据 release.py 输出路径匹配
          prerelease: true  # 是否作为预发布版本
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

